//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最終ノートで停止.
        /// </summary>
        public static string AbortAtLastNote {
            get {
                return ResourceManager.GetString("AbortAtLastNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自由記述欄.
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り下げAIR.
        /// </summary>
        public static string AirDown {
            get {
                return ResourceManager.GetString("AirDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り下げ左AIR.
        /// </summary>
        public static string AirLeftDown {
            get {
                return ResourceManager.GetString("AirLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り上げ左AIR.
        /// </summary>
        public static string AirLeftUp {
            get {
                return ResourceManager.GetString("AirLeftUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り下げ右AIR.
        /// </summary>
        public static string AirRightDown {
            get {
                return ResourceManager.GetString("AirRightDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り上げ右AIR.
        /// </summary>
        public static string AirRightUp {
            get {
                return ResourceManager.GetString("AirRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振り上げAIR.
        /// </summary>
        public static string AirUp {
            get {
                return ResourceManager.GetString("AirUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アーティスト.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本情報.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面プロパティ.
        /// </summary>
        public static string BookProperty {
            get {
                return ResourceManager.GetString("BookProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参照.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリア.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コマンド.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コピー.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタム.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切り取り.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント削除.
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 難易度.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集(&amp;E).
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消しゴム.
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクスポート.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル(&amp;F).
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択範囲内ノーツを反転.
        /// </summary>
        public static string FlipSelectedNotes {
            get {
                return ResourceManager.GetString("FlipSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ガイド音音量(共通).
        /// </summary>
        public static string GuideVolume {
            get {
                return ResourceManager.GetString("GuideVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプを開く.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ(&amp;H).
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハイスピード.
        /// </summary>
        public static string HighSpeed {
            get {
                return ResourceManager.GetString("HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インポート.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR-ACTIONとAIRを同時に追加する.
        /// </summary>
        public static string InsertAirWithAirAction {
            get {
                return ResourceManager.GetString("InsertAirWithAirAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挿入(&amp;I).
        /// </summary>
        public static string InsertMenu {
            get {
                return ResourceManager.GetString("InsertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 先頭に1小節の空白を挿入する.
        /// </summary>
        public static string InsertSingleBlankAtBeginning {
            get {
                return ResourceManager.GetString("InsertSingleBlankAtBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジャケットファイル.
        /// </summary>
        public static string JacketFile {
            get {
                return ResourceManager.GetString("JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ショートカット設定.
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ショートカットキー.
        /// </summary>
        public static string KeyCombination {
            get {
                return ResourceManager.GetString("KeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レベル.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音源情報.
        /// </summary>
        public static string MusicInformation {
            get {
                return ResourceManager.GetString("MusicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楽曲音量.
        /// </summary>
        public static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レーン幅を狭める.
        /// </summary>
        public static string NarrowLaneWidth {
            get {
                return ResourceManager.GetString("NarrowLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規作成.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノーツデザイナー.
        /// </summary>
        public static string NotesDesigner {
            get {
                return ResourceManager.GetString("NotesDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オフセット.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 貼り付け.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反転貼り付け.
        /// </summary>
        public static string PasteFlipped {
            get {
                return ResourceManager.GetString("PasteFlipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペン.
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再生/停止.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再生(&amp;P).
        /// </summary>
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プラグイン.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やり直す.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択範囲内イベントを削除.
        /// </summary>
        public static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択範囲内ノーツを削除.
        /// </summary>
        public static string RemoveSelectedNotes {
            get {
                return ResourceManager.GetString("RemoveSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期化.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前を付けて保存.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上書き保存.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 譜面プレビュー.
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて選択.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初から現在位置まで選択.
        /// </summary>
        public static string SelectToBeginning {
            get {
                return ResourceManager.GetString("SelectToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在位置から最後まで選択.
        /// </summary>
        public static string SelectToEnd {
            get {
                return ResourceManager.GetString("SelectToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDE(中継点).
        /// </summary>
        public static string SlideStep {
            get {
                return ResourceManager.GetString("SlideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音源ファイル.
        /// </summary>
        public static string SoundFile {
            get {
                return ResourceManager.GetString("SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拍子.
        /// </summary>
        public static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイトル.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元に戻す.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン情報.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示(&amp;V).
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レーン幅を広げる.
        /// </summary>
        public static string WidenLaneWidth {
            get {
                return ResourceManager.GetString("WidenLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拡大.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 縮小.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
