//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   最終ノートで停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AbortAtLastNote {
            get {
                return ResourceManager.GetString("AbortAtLastNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自由記述欄 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdditionalData {
            get {
                return ResourceManager.GetString("AdditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り下げAIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirDown {
            get {
                return ResourceManager.GetString("AirDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り下げ左AIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirLeftDown {
            get {
                return ResourceManager.GetString("AirLeftDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り上げ左AIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirLeftUp {
            get {
                return ResourceManager.GetString("AirLeftUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り下げ右AIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirRightDown {
            get {
                return ResourceManager.GetString("AirRightDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り上げ右AIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirRightUp {
            get {
                return ResourceManager.GetString("AirRightUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り上げAIR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AirUp {
            get {
                return ResourceManager.GetString("AirUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーティスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   譜面プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookProperty {
            get {
                return ResourceManager.GetString("BookProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲内のノーツチャンネルを移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeChannelSelectedNotes {
            get {
                return ResourceManager.GetString("ChangeChannelSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelMenu {
            get {
                return ResourceManager.GetString("ChannelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネル別編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelMovable {
            get {
                return ResourceManager.GetString("ChannelMovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノーツ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelNote {
            get {
                return ResourceManager.GetString("ChannelNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブルー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シアン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorCyan {
            get {
                return ResourceManager.GetString("ColorCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorGreen {
            get {
                return ResourceManager.GetString("ColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グレー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorNeutral {
            get {
                return ResourceManager.GetString("ColorNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パープル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorPurple {
            get {
                return ResourceManager.GetString("ColorPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レッド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorRed {
            get {
                return ResourceManager.GetString("ColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イエロー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorYellow {
            get {
                return ResourceManager.GetString("ColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イベント削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   難易度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消しゴム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲内ノーツを反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlipSelectedNotes {
            get {
                return ResourceManager.GetString("FlipSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイド音音量(共通) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GuideVolume {
            get {
                return ResourceManager.GetString("GuideVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハイスピード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HighSpeed {
            get {
                return ResourceManager.GetString("HighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIR-ACTIONとAIRを同時に追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsertAirWithAirAction {
            get {
                return ResourceManager.GetString("InsertAirWithAirAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   挿入(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsertMenu {
            get {
                return ResourceManager.GetString("InsertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先頭に1小節の空白を挿入する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsertSingleBlankAtBeginning {
            get {
                return ResourceManager.GetString("InsertSingleBlankAtBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昇格試験用の譜面 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isSiken {
            get {
                return ResourceManager.GetString("isSiken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オンにするとレーンオフセット、チャンネル分けソフランが使用できなくなります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isSikendis {
            get {
                return ResourceManager.GetString("isSikendis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジャケットファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JacketFile {
            get {
                return ResourceManager.GetString("JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカット設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカットキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyCombination {
            get {
                return ResourceManager.GetString("KeyCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaneMenu {
            get {
                return ResourceManager.GetString("LaneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーンオフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaneOffset {
            get {
                return ResourceManager.GetString("LaneOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChartCyanvas限定の拡張仕様です。(susのみ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaneOffsetdis {
            get {
                return ResourceManager.GetString("LaneOffsetdis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーン表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LaneVisual {
            get {
                return ResourceManager.GetString("LaneVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音源情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MusicInformation {
            get {
                return ResourceManager.GetString("MusicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽曲音量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーン幅を狭める に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NarrowLaneWidth {
            get {
                return ResourceManager.GetString("NarrowLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノーツデザイナー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotesDesigner {
            get {
                return ResourceManager.GetString("NotesDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   反転貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteFlipped {
            get {
                return ResourceManager.GetString("PasteFlipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセカ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PJsekai {
            get {
                return ResourceManager.GetString("PJsekai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生/停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlayMenu {
            get {
                return ResourceManager.GetString("PlayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲内イベントを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲内ノーツを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveSelectedNotes {
            get {
                return ResourceManager.GetString("RemoveSelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   譜面プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScorePreview {
            get {
                return ResourceManager.GetString("ScorePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最初から現在位置まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectToBeginning {
            get {
                return ResourceManager.GetString("SelectToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在位置から最後まで選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectToEnd {
            get {
                return ResourceManager.GetString("SelectToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SLIDE(中継点) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideStep {
            get {
                return ResourceManager.GetString("SlideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スロー再生 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlowDownPreview {
            get {
                return ResourceManager.GetString("SlowDownPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音源ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SoundFile {
            get {
                return ResourceManager.GetString("SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステップのチャンネル移動なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string steptype1 {
            get {
                return ResourceManager.GetString("steptype1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステップのチャンネル移動あり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string steptype2 {
            get {
                return ResourceManager.GetString("steptype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeBlack {
            get {
                return ResourceManager.GetString("ThemeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeMenu {
            get {
                return ResourceManager.GetString("ThemeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホワイト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeWhite {
            get {
                return ResourceManager.GetString("ThemeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拍子 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示(&amp;V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Visual1 {
            get {
                return ResourceManager.GetString("Visual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半透明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Visual2 {
            get {
                return ResourceManager.GetString("Visual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Visual3 {
            get {
                return ResourceManager.GetString("Visual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーン幅を広げる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WidenLaneWidth {
            get {
                return ResourceManager.GetString("WidenLaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縮小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
