//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.PluginStrings", typeof(PluginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンボ計算.
        /// </summary>
        public static string ComboCalculator {
            get {
                return ResourceManager.GetString("ComboCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スライド編み込み.
        /// </summary>
        public static string SlideKnitter {
            get {
                return ResourceManager.GetString("SlideKnitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スライド結合.
        /// </summary>
        public static string SlideMerger {
            get {
                return ResourceManager.GetString("SlideMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スライド時間軸反転.
        /// </summary>
        public static string SlideReverser {
            get {
                return ResourceManager.GetString("SlideReverser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スライド分割.
        /// </summary>
        public static string SlideSplitter {
            get {
                return ResourceManager.GetString("SlideSplitter", resourceCulture);
            }
        }
    }
}
