//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.PluginStrings", typeof(PluginStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コンボ計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboCalculator {
            get {
                return ResourceManager.GetString("ComboCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド編み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideKnitter {
            get {
                return ResourceManager.GetString("SlideKnitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド結合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideMerger {
            get {
                return ResourceManager.GetString("SlideMerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド時間軸反転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideReverser {
            get {
                return ResourceManager.GetString("SlideReverser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド分割 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlideSplitter {
            get {
                return ResourceManager.GetString("SlideSplitter", resourceCulture);
            }
        }
    }
}
